source "https://rubygems.org"
ruby "~> 2.5"

gem "rake"

gem "jekyll", "~> 4.2"
group :jekyll_plugins do
  gem "jekyll-last-modified-at" # used for sitemap
  gem "jekyll-sitemap"
  gem "jekyll-tidy"
  gem "jekyll-toc"
  gem "jekyll-regex-replace"
  gem "jekyll-pandoc"
end
