# clean jekyll output folder
require 'rake/clean'
CLEAN.include(FileList['_site'])

task :build => ["clean"] do
    ENV['JEKYLL_ENV'] = 'production'
    Dir.chdir(File.dirname(__FILE__)) do
        sh "bundle", "exec", "jekyll", "clean"
        sh "bundle", "exec", "jekyll", "build"
    end
end

task :start do
    ENV['JEKYLL_ENV'] = 'development'
    Dir.chdir(File.dirname(__FILE__)) do
        sh "bundle", "exec", "jekyll", "build"
        sh "bundle", "exec", "jekyll", "serve"
    end
end
