#!/bin/sh
#
# This file is part of personal-website which is released under MIT license.
# See file LICENSE.txt or go to https://github.com/matejkosiarcik/personal-website for full license details.
#

# setup
set -euf
cd "$(dirname "${0}")/.."
. "./util/helpers.sh"

# config output
output="build/doc"
rm -rf "${output}" && mkdir -p "${output}"

# Markdown
if check grip; then
    git_files | while IFS= read -r file; do
        if has_suffix "${file}" ".md"; then
            # declare variables
            target="${output}/$(dirname "${file}")/$(basename "${file}" ".md").html"
            dir="$(dirname "${target}")"
            filename="$(basename "${target}")"

            # export to  html
            mkdir -p "${dir}"
            grip "${file}" --export "${target}" 2>/dev/null

            # if the markdown is README, create symlink to it from index.html
            if has_prefix "${filename}" "README"; then ln -s "${filename}" "${dir}/index.html"; fi
        fi
    done
fi
