#!/bin/sh
#
# format
# Copyright © 2017 Matej Kosiarcik. All rights reserved.
# This file contains formatting procedures for project [re]sources
#

# setup
set -euf
cd "$(dirname "${0}")/.."
. "./util/helpers.sh"

# All files
text_files | while IFS= read -r file; do
    strip "${file}"
done

# Shell
if check shfmt; then
    shell_files | while IFS= read -r file; do
        shfmt -i 4 -p -w "${file}"
    done
fi

# JSON
if check jsonlint; then
    json_files | while IFS= read -r file; do
        printf "%s\n" "$(jsonlint "${file}" --indent 4 --pretty-print)" >"${file}"
    done
fi
