#!/bin/sh
#
# Copyright © 2017 Matej Kosiarcik <matejkosiarcik@gmail.com>. All rights reserved.
# This file is part of personal-website which is released under MIT license.
# See file LICENSE.txt or go to https://github.com/matejkosiarcik/personal-website for full license details.
#

# setup
set -euf
cd "$(dirname "${0}")/.."
. "./util/helpers.sh"

# All files
text_files | while IFS= read -r file; do
    strip "${file}"
done

# Shell
if check shfmt; then
    shell_files | while IFS= read -r file; do
        shfmt -i 4 -p -w "${file}"
    done
fi

# JSON
if check jsonlint; then
    json_files | while IFS= read -r file; do
        printf "%s\n" "$(jsonlint "${file}" --indent 4 --pretty-print)" >"${file}"
    done
fi

# Python
if check autopep8; then
    autopep8 "." --recursive --in-place --aggressive --aggressive
fi
