#!/bin/sh
#
# prepare
# Copyright © 2017 Matej Kosiarcik. All rights reserved.
# This file runs before build
#

# setup
set -euf
cd "$(dirname "${0}")"
. "./helpers.sh"
cd ".."

# Run this pre-build stages
# format should run before lint, because we want issues in sources that are possible to autofix to be fixed right away
# codegen should run after format, because we want issues in generated code to be picked up by lint, so we can fix the template
# lint should run last, because we want to report only issues that could not be fixed in format and also issues with generated code
./Tools/format
./Tools/lint
