#!/bin/sh
#
# Copyright © 2017 Matej Kosiarcik <matejkosiarcik@gmail.com>. All rights reserved.
# This file is part of personal-website which is released under MIT license.
# See file LICENSE.txt or go to https://github.com/matejkosiarcik/personal-website for full license details.
#

# setup
set -euf
cd "$(dirname "${0}")/.."
. "./util/helpers.sh"

# Run this pre-build stages
# format should run before lint, because we want issues in sources that are possible to autofix to be fixed right away
# generation should run after format, because we want issues in generated code to be picked up by lint, so we can fix the template
# lint should run last, because we want to report only issues that could not be fixed in format and also issues with generated code
"./util/format"
"./util/docgen"
"./util/lint"
