#!/bin/sh
#
# Copyright © 2017 Matej Kosiarcik <matejkosiarcik@gmail.com>. All rights reserved.
# This file is part of Web which is released under MIT license.
# See file LICENSE.txt or go to https://github.com/matejkosiarcik/Web/ for full license details.
#

# setup
set -euf
cd "$(dirname "${0}")/.."
. "./util/helpers.sh"

# Run classic build
if [ "${#}" -eq "0" ]; then ./Tools/build; else ./Tools/build "${@}"; fi
