#!/bin/sh
#
# test
# Copyright © 2017 Matej Kosiarcik. All rights reserved.
# This file tests project
#

# setup
set -euf
cd "$(dirname "${0}")"
. "./helpers.sh"
cd ".."

# Run classic build
if [ "${#}" -eq "0" ]; then ./Tools/build; else ./Tools/build "${@}"; fi
