#!/bin/sh
#
# This file is part of personal-website which is released under MIT license.
# See file LICENSE.txt or go to https://github.com/matejkosiarcik/personal-website for full license details.
#

# setup
set -euf
cd "$(dirname "${0}")/.."
. "./utils/internal/helpers.sh"

# All text files
text_files | while IFS= read -r file; do
    strip "${file}"
done

# JSON
if check jsonlint; then
    files_ending ".json" | while IFS= read -r file; do
        if [ "${file}" = "tslint.json" ]; then continue; fi
        printf "%s\n" "$(jsonlint "${file}" --indent 4 --pretty-print)" >"${file}"
    done
fi

# Python
if check autopep8; then
    autopep8 "." --recursive --in-place --aggressive --aggressive
fi

# Swift
if check swiftlint; then
    swiftlint autocorrect 2>/dev/null
fi

# Shell
if check shfmt; then
    shell_files | while IFS= read -r file; do
        shfmt -i 4 -p -w "${file}"
    done
fi

# SVG
if check svgcleaner && check xmllint; then
    files_ending ".svg" | while IFS= read -r file; do
        printf "%s\n" "$(svgcleaner "${file}" --multipass --stdout --quiet --coordinates-precision 1 --properties-precision 1 \
            --transforms-precision 1 --paths-coordinates-precision 1 | xmllint --format -)" >"${file}"
    done
fi
