#!/bin/sh
#
# This file is part of personal-website which is released under MIT license.
# See file LICENSE.txt or go to https://github.com/matejkosiarcik/personal-website for full license details.
#

# setup
set -euf
cd "$(dirname "${0}")/.."
. "./utils/internal/helpers.sh"

# All text files
text_files | while IFS= read -r file; do
    strip_file "${file}"
done

# JSON
if check jsonlint; then
    project_files | grep -E '.json$' | while IFS= read -r file; do
        if [ "${file}" = "tslint.json" ]; then continue; fi
        printf "%s\n" "$(jsonlint "${file}" --indent 4 --pretty-print)" >"${file}"
    done
fi

# Python
if check autopep8; then
    autopep8 "." --recursive --in-place
fi

# Swift
if check swiftlint; then
    swiftlint autocorrect 2>/dev/null
fi

# Shell
if check shfmt; then
    shell_files | while IFS= read -r file; do
        shfmt -i 4 -p -w "${file}"
    done
fi

# SVG
if check svgcleaner && check xmllint; then
    project_files | grep -E '.svg$' | while IFS= read -r file; do
        svgcleaner "${file}" "${file}" --quiet --multipass \
            --coordinates-precision 1 --properties-precision 1 --transforms-precision 3 --paths-coordinates-precision 1 \
            --convert-shapes no
        printf "%s\n" "$(xmllint --format "${file}")" >"${file}"
    done
fi
